//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Audire_EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Audire_dbEntities : DbContext
    {
        public Audire_dbEntities()
            : base("name=Audire_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_country_master> tbl_country_master { get; set; }
        public DbSet<tbl_location_master> tbl_location_master { get; set; }
        public DbSet<tbl_Module_master> tbl_Module_master { get; set; }
        public DbSet<tbl_region_master> tbl_region_master { get; set; }
        public DbSet<tbl_line_master> tbl_line_master { get; set; }
        public DbSet<tbl_user_master> tbl_user_master { get; set; }
        public DbSet<Menu_List> Menu_List { get; set; }
        public DbSet<tbl_audit_plan> tbl_audit_plan { get; set; }
        public DbSet<tbl_audit_type> tbl_audit_type { get; set; }
        public DbSet<tbl_AuditResult> tbl_AuditResult { get; set; }
        public DbSet<tbl_distribution_list> tbl_distribution_list { get; set; }
        public DbSet<tbl_group_master> tbl_group_master { get; set; }
        public DbSet<tbl_group_members> tbl_group_members { get; set; }
        public DbSet<tbl_line_product_relationship> tbl_line_product_relationship { get; set; }
        public DbSet<tbl_local_answers> tbl_local_answers { get; set; }
        public DbSet<tbl_local_answers_bak> tbl_local_answers_bak { get; set; }
        public DbSet<tbl_local_question_master> tbl_local_question_master { get; set; }
        public DbSet<tbl_process_master> tbl_process_master { get; set; }
        public DbSet<tbl_product_master> tbl_product_master { get; set; }
        public DbSet<tbl_question_master> tbl_question_master { get; set; }
        public DbSet<tbl_section_master> tbl_section_master { get; set; }
        public DbSet<tbl_sub_section_master> tbl_sub_section_master { get; set; }
        public DbSet<tbl_permissions> tbl_permissions { get; set; }
        public DbSet<tbl_role_master> tbl_role_master { get; set; }
    
        public virtual ObjectResult<sp_getProductListforEdit_Result> sp_getProductListforEdit(Nullable<int> p_user_id)
        {
            var p_user_idParameter = p_user_id.HasValue ?
                new ObjectParameter("p_user_id", p_user_id) :
                new ObjectParameter("p_user_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getProductListforEdit_Result>("sp_getProductListforEdit", p_user_idParameter);
        }
    
        public virtual int sp_checkAuthentication(string username, string password, string userID, string deviceID, ObjectParameter l_err_code, ObjectParameter l_err_message)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var userIDParameter = userID != null ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(string));
    
            var deviceIDParameter = deviceID != null ?
                new ObjectParameter("deviceID", deviceID) :
                new ObjectParameter("deviceID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_checkAuthentication", usernameParameter, passwordParameter, userIDParameter, deviceIDParameter, l_err_code, l_err_message);
        }
    
        public virtual ObjectResult<sp_DelPart_Result> sp_DelPart(Nullable<int> p_line_id, Nullable<int> p_product_id, ObjectParameter l_err_code, ObjectParameter l_err_message)
        {
            var p_line_idParameter = p_line_id.HasValue ?
                new ObjectParameter("p_line_id", p_line_id) :
                new ObjectParameter("p_line_id", typeof(int));
    
            var p_product_idParameter = p_product_id.HasValue ?
                new ObjectParameter("p_product_id", p_product_id) :
                new ObjectParameter("p_product_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_DelPart_Result>("sp_DelPart", p_line_idParameter, p_product_idParameter, l_err_code, l_err_message);
        }
    
        public virtual ObjectResult<sp_GetAuditPlan_Result> sp_GetAuditPlan(Nullable<int> p_location_id, Nullable<int> p_module_id, Nullable<int> p_line_id, Nullable<int> p_user_id)
        {
            var p_location_idParameter = p_location_id.HasValue ?
                new ObjectParameter("p_location_id", p_location_id) :
                new ObjectParameter("p_location_id", typeof(int));
    
            var p_module_idParameter = p_module_id.HasValue ?
                new ObjectParameter("p_module_id", p_module_id) :
                new ObjectParameter("p_module_id", typeof(int));
    
            var p_line_idParameter = p_line_id.HasValue ?
                new ObjectParameter("p_line_id", p_line_id) :
                new ObjectParameter("p_line_id", typeof(int));
    
            var p_user_idParameter = p_user_id.HasValue ?
                new ObjectParameter("p_user_id", p_user_id) :
                new ObjectParameter("p_user_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetAuditPlan_Result>("sp_GetAuditPlan", p_location_idParameter, p_module_idParameter, p_line_idParameter, p_user_idParameter);
        }
    
        public virtual int sp_getCountryId(string p_country_code, string p_country_name, ObjectParameter l_country_id)
        {
            var p_country_codeParameter = p_country_code != null ?
                new ObjectParameter("p_country_code", p_country_code) :
                new ObjectParameter("p_country_code", typeof(string));
    
            var p_country_nameParameter = p_country_name != null ?
                new ObjectParameter("p_country_name", p_country_name) :
                new ObjectParameter("p_country_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_getCountryId", p_country_codeParameter, p_country_nameParameter, l_country_id);
        }
    
        public virtual ObjectResult<sp_GetCountryList_Result> sp_GetCountryList(Nullable<int> p_region_id, Nullable<int> module_id)
        {
            var p_region_idParameter = p_region_id.HasValue ?
                new ObjectParameter("p_region_id", p_region_id) :
                new ObjectParameter("p_region_id", typeof(int));
    
            var module_idParameter = module_id.HasValue ?
                new ObjectParameter("module_id", module_id) :
                new ObjectParameter("module_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetCountryList_Result>("sp_GetCountryList", p_region_idParameter, module_idParameter);
        }
    
        public virtual int sp_getLineId(string p_region_name, Nullable<int> p_region_id, string p_country_name, Nullable<int> p_country_id, string p_location_name, Nullable<int> p_location_id, string p_line_name, ObjectParameter l_line_id)
        {
            var p_region_nameParameter = p_region_name != null ?
                new ObjectParameter("p_region_name", p_region_name) :
                new ObjectParameter("p_region_name", typeof(string));
    
            var p_region_idParameter = p_region_id.HasValue ?
                new ObjectParameter("p_region_id", p_region_id) :
                new ObjectParameter("p_region_id", typeof(int));
    
            var p_country_nameParameter = p_country_name != null ?
                new ObjectParameter("p_country_name", p_country_name) :
                new ObjectParameter("p_country_name", typeof(string));
    
            var p_country_idParameter = p_country_id.HasValue ?
                new ObjectParameter("p_country_id", p_country_id) :
                new ObjectParameter("p_country_id", typeof(int));
    
            var p_location_nameParameter = p_location_name != null ?
                new ObjectParameter("p_location_name", p_location_name) :
                new ObjectParameter("p_location_name", typeof(string));
    
            var p_location_idParameter = p_location_id.HasValue ?
                new ObjectParameter("p_location_id", p_location_id) :
                new ObjectParameter("p_location_id", typeof(int));
    
            var p_line_nameParameter = p_line_name != null ?
                new ObjectParameter("p_line_name", p_line_name) :
                new ObjectParameter("p_line_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_getLineId", p_region_nameParameter, p_region_idParameter, p_country_nameParameter, p_country_idParameter, p_location_nameParameter, p_location_idParameter, p_line_nameParameter, l_line_id);
        }
    
        public virtual ObjectResult<sp_GetLinesForLocation_Result> sp_GetLinesForLocation(Nullable<int> p_location_id, Nullable<int> module_id)
        {
            var p_location_idParameter = p_location_id.HasValue ?
                new ObjectParameter("p_location_id", p_location_id) :
                new ObjectParameter("p_location_id", typeof(int));
    
            var module_idParameter = module_id.HasValue ?
                new ObjectParameter("module_id", module_id) :
                new ObjectParameter("module_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetLinesForLocation_Result>("sp_GetLinesForLocation", p_location_idParameter, module_idParameter);
        }
    
        public virtual int sp_getLocationId(string p_location_code, string p_location_name, ObjectParameter l_location_id)
        {
            var p_location_codeParameter = p_location_code != null ?
                new ObjectParameter("p_location_code", p_location_code) :
                new ObjectParameter("p_location_code", typeof(string));
    
            var p_location_nameParameter = p_location_name != null ?
                new ObjectParameter("p_location_name", p_location_name) :
                new ObjectParameter("p_location_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_getLocationId", p_location_codeParameter, p_location_nameParameter, l_location_id);
        }
    
        public virtual ObjectResult<sp_GetLocationList_Result> sp_GetLocationList(Nullable<int> p_country_id, Nullable<int> module_id)
        {
            var p_country_idParameter = p_country_id.HasValue ?
                new ObjectParameter("p_country_id", p_country_id) :
                new ObjectParameter("p_country_id", typeof(int));
    
            var module_idParameter = module_id.HasValue ?
                new ObjectParameter("module_id", module_id) :
                new ObjectParameter("module_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetLocationList_Result>("sp_GetLocationList", p_country_idParameter, module_idParameter);
        }
    
        public virtual int sp_GetLocations(Nullable<int> p_user_id)
        {
            var p_user_idParameter = p_user_id.HasValue ?
                new ObjectParameter("p_user_id", p_user_id) :
                new ObjectParameter("p_user_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GetLocations", p_user_idParameter);
        }
    
        public virtual ObjectResult<sp_GetMailDetailsForReport_Result> sp_GetMailDetailsForReport(Nullable<int> audit_id)
        {
            var audit_idParameter = audit_id.HasValue ?
                new ObjectParameter("audit_id", audit_id) :
                new ObjectParameter("audit_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetMailDetailsForReport_Result>("sp_GetMailDetailsForReport", audit_idParameter);
        }
    
        public virtual ObjectResult<sp_GetModuleList_Result> sp_GetModuleList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetModuleList_Result>("sp_GetModuleList");
        }
    
        public virtual ObjectResult<sp_getOpenTasks_Result> sp_getOpenTasks(Nullable<int> p_region_id, Nullable<int> p_country_id, Nullable<int> p_location_id, Nullable<int> p_line_id, Nullable<int> module_id, Nullable<int> auditType_id, Nullable<int> p_user_id)
        {
            var p_region_idParameter = p_region_id.HasValue ?
                new ObjectParameter("p_region_id", p_region_id) :
                new ObjectParameter("p_region_id", typeof(int));
    
            var p_country_idParameter = p_country_id.HasValue ?
                new ObjectParameter("p_country_id", p_country_id) :
                new ObjectParameter("p_country_id", typeof(int));
    
            var p_location_idParameter = p_location_id.HasValue ?
                new ObjectParameter("p_location_id", p_location_id) :
                new ObjectParameter("p_location_id", typeof(int));
    
            var p_line_idParameter = p_line_id.HasValue ?
                new ObjectParameter("p_line_id", p_line_id) :
                new ObjectParameter("p_line_id", typeof(int));
    
            var module_idParameter = module_id.HasValue ?
                new ObjectParameter("module_id", module_id) :
                new ObjectParameter("module_id", typeof(int));
    
            var auditType_idParameter = auditType_id.HasValue ?
                new ObjectParameter("auditType_id", auditType_id) :
                new ObjectParameter("auditType_id", typeof(int));
    
            var p_user_idParameter = p_user_id.HasValue ?
                new ObjectParameter("p_user_id", p_user_id) :
                new ObjectParameter("p_user_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getOpenTasks_Result>("sp_getOpenTasks", p_region_idParameter, p_country_idParameter, p_location_idParameter, p_line_idParameter, module_idParameter, auditType_idParameter, p_user_idParameter);
        }
    
        public virtual ObjectResult<sp_GetProcessList_Result> sp_GetProcessList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetProcessList_Result>("sp_GetProcessList");
        }
    
        public virtual int sp_getProductId(string p_product_code, string p_product_name, ObjectParameter l_product_id)
        {
            var p_product_codeParameter = p_product_code != null ?
                new ObjectParameter("p_product_code", p_product_code) :
                new ObjectParameter("p_product_code", typeof(string));
    
            var p_product_nameParameter = p_product_name != null ?
                new ObjectParameter("p_product_name", p_product_name) :
                new ObjectParameter("p_product_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_getProductId", p_product_codeParameter, p_product_nameParameter, l_product_id);
        }
    
        public virtual ObjectResult<sp_GetProductsForLine_Result> sp_GetProductsForLine(Nullable<int> p_line_id, Nullable<int> module_id)
        {
            var p_line_idParameter = p_line_id.HasValue ?
                new ObjectParameter("p_line_id", p_line_id) :
                new ObjectParameter("p_line_id", typeof(int));
    
            var module_idParameter = module_id.HasValue ?
                new ObjectParameter("module_id", module_id) :
                new ObjectParameter("module_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetProductsForLine_Result>("sp_GetProductsForLine", p_line_idParameter, module_idParameter);
        }
    
        public virtual ObjectResult<sp_getQuestionList_Result> sp_getQuestionList(Nullable<int> module_id, Nullable<int> auditType_id, Nullable<int> l_location_id)
        {
            var module_idParameter = module_id.HasValue ?
                new ObjectParameter("module_id", module_id) :
                new ObjectParameter("module_id", typeof(int));
    
            var auditType_idParameter = auditType_id.HasValue ?
                new ObjectParameter("auditType_id", auditType_id) :
                new ObjectParameter("auditType_id", typeof(int));
    
            var l_location_idParameter = l_location_id.HasValue ?
                new ObjectParameter("l_location_id", l_location_id) :
                new ObjectParameter("l_location_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getQuestionList_Result>("sp_getQuestionList", module_idParameter, auditType_idParameter, l_location_idParameter);
        }
    
        public virtual int sp_getRegionId(string p_region_code, string p_region_name, ObjectParameter l_region_id)
        {
            var p_region_codeParameter = p_region_code != null ?
                new ObjectParameter("p_region_code", p_region_code) :
                new ObjectParameter("p_region_code", typeof(string));
    
            var p_region_nameParameter = p_region_name != null ?
                new ObjectParameter("p_region_name", p_region_name) :
                new ObjectParameter("p_region_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_getRegionId", p_region_codeParameter, p_region_nameParameter, l_region_id);
        }
    
        public virtual ObjectResult<sp_GetRegionList_Result> sp_GetRegionList(string username, Nullable<int> module_id)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var module_idParameter = module_id.HasValue ?
                new ObjectParameter("module_id", module_id) :
                new ObjectParameter("module_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetRegionList_Result>("sp_GetRegionList", usernameParameter, module_idParameter);
        }
    
        public virtual int sp_InsCountry(Nullable<int> p_country_id, string p_country_code, string p_country_name)
        {
            var p_country_idParameter = p_country_id.HasValue ?
                new ObjectParameter("p_country_id", p_country_id) :
                new ObjectParameter("p_country_id", typeof(int));
    
            var p_country_codeParameter = p_country_code != null ?
                new ObjectParameter("p_country_code", p_country_code) :
                new ObjectParameter("p_country_code", typeof(string));
    
            var p_country_nameParameter = p_country_name != null ?
                new ObjectParameter("p_country_name", p_country_name) :
                new ObjectParameter("p_country_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsCountry", p_country_idParameter, p_country_codeParameter, p_country_nameParameter);
        }
    
        public virtual int sp_InsLine(Nullable<int> p_line_id, string p_region_name, string p_country_name, string p_location_name, string p_line_code, string p_line_name, string p_distribution_list, ObjectParameter l_err_code, ObjectParameter l_err_message)
        {
            var p_line_idParameter = p_line_id.HasValue ?
                new ObjectParameter("p_line_id", p_line_id) :
                new ObjectParameter("p_line_id", typeof(int));
    
            var p_region_nameParameter = p_region_name != null ?
                new ObjectParameter("p_region_name", p_region_name) :
                new ObjectParameter("p_region_name", typeof(string));
    
            var p_country_nameParameter = p_country_name != null ?
                new ObjectParameter("p_country_name", p_country_name) :
                new ObjectParameter("p_country_name", typeof(string));
    
            var p_location_nameParameter = p_location_name != null ?
                new ObjectParameter("p_location_name", p_location_name) :
                new ObjectParameter("p_location_name", typeof(string));
    
            var p_line_codeParameter = p_line_code != null ?
                new ObjectParameter("p_line_code", p_line_code) :
                new ObjectParameter("p_line_code", typeof(string));
    
            var p_line_nameParameter = p_line_name != null ?
                new ObjectParameter("p_line_name", p_line_name) :
                new ObjectParameter("p_line_name", typeof(string));
    
            var p_distribution_listParameter = p_distribution_list != null ?
                new ObjectParameter("p_distribution_list", p_distribution_list) :
                new ObjectParameter("p_distribution_list", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsLine", p_line_idParameter, p_region_nameParameter, p_country_nameParameter, p_location_nameParameter, p_line_codeParameter, p_line_nameParameter, p_distribution_listParameter, l_err_code, l_err_message);
        }
    
        public virtual int sp_InsLineProduct(Nullable<int> p_line_product_rel_id, string p_region_name, string p_country_name, string p_location_name, string p_line_name, string p_product_code, Nullable<System.DateTime> p_start_date, Nullable<System.DateTime> p_end_date, ObjectParameter l_err_code, ObjectParameter l_err_message)
        {
            var p_line_product_rel_idParameter = p_line_product_rel_id.HasValue ?
                new ObjectParameter("p_line_product_rel_id", p_line_product_rel_id) :
                new ObjectParameter("p_line_product_rel_id", typeof(int));
    
            var p_region_nameParameter = p_region_name != null ?
                new ObjectParameter("p_region_name", p_region_name) :
                new ObjectParameter("p_region_name", typeof(string));
    
            var p_country_nameParameter = p_country_name != null ?
                new ObjectParameter("p_country_name", p_country_name) :
                new ObjectParameter("p_country_name", typeof(string));
    
            var p_location_nameParameter = p_location_name != null ?
                new ObjectParameter("p_location_name", p_location_name) :
                new ObjectParameter("p_location_name", typeof(string));
    
            var p_line_nameParameter = p_line_name != null ?
                new ObjectParameter("p_line_name", p_line_name) :
                new ObjectParameter("p_line_name", typeof(string));
    
            var p_product_codeParameter = p_product_code != null ?
                new ObjectParameter("p_product_code", p_product_code) :
                new ObjectParameter("p_product_code", typeof(string));
    
            var p_start_dateParameter = p_start_date.HasValue ?
                new ObjectParameter("p_start_date", p_start_date) :
                new ObjectParameter("p_start_date", typeof(System.DateTime));
    
            var p_end_dateParameter = p_end_date.HasValue ?
                new ObjectParameter("p_end_date", p_end_date) :
                new ObjectParameter("p_end_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsLineProduct", p_line_product_rel_idParameter, p_region_nameParameter, p_country_nameParameter, p_location_nameParameter, p_line_nameParameter, p_product_codeParameter, p_start_dateParameter, p_end_dateParameter, l_err_code, l_err_message);
        }
    
        public virtual int sp_InsRegion(Nullable<int> p_region_id, string p_region_code, string p_region_name)
        {
            var p_region_idParameter = p_region_id.HasValue ?
                new ObjectParameter("p_region_id", p_region_id) :
                new ObjectParameter("p_region_id", typeof(int));
    
            var p_region_codeParameter = p_region_code != null ?
                new ObjectParameter("p_region_code", p_region_code) :
                new ObjectParameter("p_region_code", typeof(string));
    
            var p_region_nameParameter = p_region_name != null ?
                new ObjectParameter("p_region_name", p_region_name) :
                new ObjectParameter("p_region_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsRegion", p_region_idParameter, p_region_codeParameter, p_region_nameParameter);
        }
    
        public virtual int sp_saveProduct(Nullable<int> p_product_id, string p_product_code)
        {
            var p_product_idParameter = p_product_id.HasValue ?
                new ObjectParameter("p_product_id", p_product_id) :
                new ObjectParameter("p_product_id", typeof(int));
    
            var p_product_codeParameter = p_product_code != null ?
                new ObjectParameter("p_product_code", p_product_code) :
                new ObjectParameter("p_product_code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_saveProduct", p_product_idParameter, p_product_codeParameter);
        }
    
        public virtual ObjectResult<sp_UserLogin_Result> sp_UserLogin(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_UserLogin_Result>("sp_UserLogin", usernameParameter, passwordParameter);
        }
    
        [EdmFunction("Audire_dbEntities", "SplitString")]
        public virtual IQueryable<string> SplitString(string input, string character)
        {
            var inputParameter = input != null ?
                new ObjectParameter("Input", input) :
                new ObjectParameter("Input", typeof(string));
    
            var characterParameter = character != null ?
                new ObjectParameter("Character", character) :
                new ObjectParameter("Character", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<string>("[Audire_dbEntities].[SplitString](@Input, @Character)", inputParameter, characterParameter);
        }
    
        public virtual ObjectResult<sp_getAuditType_Result> sp_getAuditType(Nullable<int> module_id)
        {
            var module_idParameter = module_id.HasValue ?
                new ObjectParameter("module_id", module_id) :
                new ObjectParameter("module_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getAuditType_Result>("sp_getAuditType", module_idParameter);
        }
    
        public virtual ObjectResult<sp_getQuestionListForC_Result> sp_getQuestionListForC(Nullable<int> module_id, Nullable<int> auditType_id, Nullable<int> l_location_id)
        {
            var module_idParameter = module_id.HasValue ?
                new ObjectParameter("module_id", module_id) :
                new ObjectParameter("module_id", typeof(int));
    
            var auditType_idParameter = auditType_id.HasValue ?
                new ObjectParameter("auditType_id", auditType_id) :
                new ObjectParameter("auditType_id", typeof(int));
    
            var l_location_idParameter = l_location_id.HasValue ?
                new ObjectParameter("l_location_id", l_location_id) :
                new ObjectParameter("l_location_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getQuestionListForC_Result>("sp_getQuestionListForC", module_idParameter, auditType_idParameter, l_location_idParameter);
        }
    
        public virtual ObjectResult<sp_getProcessEmpMapping_Result> sp_getProcessEmpMapping()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getProcessEmpMapping_Result>("sp_getProcessEmpMapping");
        }
    
        public virtual int sp_InsAuditPlan(Nullable<int> p_audit_plan_id, Nullable<int> p_user_id, Nullable<System.DateTime> p_planned_date, Nullable<System.DateTime> p_planned_date_end, Nullable<int> l_location_id, Nullable<int> module_id, Nullable<int> audit_type_id, string audit_note, ObjectParameter l_invite_to_list, ObjectParameter l_err_code, ObjectParameter l_err_message)
        {
            var p_audit_plan_idParameter = p_audit_plan_id.HasValue ?
                new ObjectParameter("p_audit_plan_id", p_audit_plan_id) :
                new ObjectParameter("p_audit_plan_id", typeof(int));
    
            var p_user_idParameter = p_user_id.HasValue ?
                new ObjectParameter("p_user_id", p_user_id) :
                new ObjectParameter("p_user_id", typeof(int));
    
            var p_planned_dateParameter = p_planned_date.HasValue ?
                new ObjectParameter("p_planned_date", p_planned_date) :
                new ObjectParameter("p_planned_date", typeof(System.DateTime));
    
            var p_planned_date_endParameter = p_planned_date_end.HasValue ?
                new ObjectParameter("p_planned_date_end", p_planned_date_end) :
                new ObjectParameter("p_planned_date_end", typeof(System.DateTime));
    
            var l_location_idParameter = l_location_id.HasValue ?
                new ObjectParameter("l_location_id", l_location_id) :
                new ObjectParameter("l_location_id", typeof(int));
    
            var module_idParameter = module_id.HasValue ?
                new ObjectParameter("module_id", module_id) :
                new ObjectParameter("module_id", typeof(int));
    
            var audit_type_idParameter = audit_type_id.HasValue ?
                new ObjectParameter("audit_type_id", audit_type_id) :
                new ObjectParameter("audit_type_id", typeof(int));
    
            var audit_noteParameter = audit_note != null ?
                new ObjectParameter("audit_note", audit_note) :
                new ObjectParameter("audit_note", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsAuditPlan", p_audit_plan_idParameter, p_user_idParameter, p_planned_dateParameter, p_planned_date_endParameter, l_location_idParameter, module_idParameter, audit_type_idParameter, audit_noteParameter, l_invite_to_list, l_err_code, l_err_message);
        }
    
        public virtual int sp_InsQuestion(string question, Nullable<int> module_id, Nullable<int> auditType_id)
        {
            var questionParameter = question != null ?
                new ObjectParameter("question", question) :
                new ObjectParameter("question", typeof(string));
    
            var module_idParameter = module_id.HasValue ?
                new ObjectParameter("module_id", module_id) :
                new ObjectParameter("module_id", typeof(int));
    
            var auditType_idParameter = auditType_id.HasValue ?
                new ObjectParameter("auditType_id", auditType_id) :
                new ObjectParameter("auditType_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsQuestion", questionParameter, module_idParameter, auditType_idParameter);
        }
    
        public virtual int GetMaxAuditId(ObjectParameter p_audit_id)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetMaxAuditId", p_audit_id);
        }
    
        public virtual ObjectResult<sp_getUserList_Result> sp_getUserList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getUserList_Result>("sp_getUserList");
        }
    
        public virtual ObjectResult<sp_getAuditScore_Result> sp_getAuditScore(Nullable<int> module_id, string scoreby, string module_name)
        {
            var module_idParameter = module_id.HasValue ?
                new ObjectParameter("Module_id", module_id) :
                new ObjectParameter("Module_id", typeof(int));
    
            var scorebyParameter = scoreby != null ?
                new ObjectParameter("scoreby", scoreby) :
                new ObjectParameter("scoreby", typeof(string));
    
            var module_nameParameter = module_name != null ?
                new ObjectParameter("module_name", module_name) :
                new ObjectParameter("module_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getAuditScore_Result>("sp_getAuditScore", module_idParameter, scorebyParameter, module_nameParameter);
        }
    
        public virtual ObjectResult<sp_getDashboardDetail_Result> sp_getDashboardDetail(Nullable<int> module_id, string module_name)
        {
            var module_idParameter = module_id.HasValue ?
                new ObjectParameter("Module_id", module_id) :
                new ObjectParameter("Module_id", typeof(int));
    
            var module_nameParameter = module_name != null ?
                new ObjectParameter("module_name", module_name) :
                new ObjectParameter("module_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getDashboardDetail_Result>("sp_getDashboardDetail", module_idParameter, module_nameParameter);
        }
    
        public virtual ObjectResult<sp_getAllTasks_Result> sp_getAllTasks()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getAllTasks_Result>("sp_getAllTasks");
        }
    
        public virtual ObjectResult<sp_getMonthlyScore_Result> sp_getMonthlyScore(Nullable<int> module_id, Nullable<int> audit_type_id)
        {
            var module_idParameter = module_id.HasValue ?
                new ObjectParameter("Module_id", module_id) :
                new ObjectParameter("Module_id", typeof(int));
    
            var audit_type_idParameter = audit_type_id.HasValue ?
                new ObjectParameter("audit_type_id", audit_type_id) :
                new ObjectParameter("audit_type_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getMonthlyScore_Result>("sp_getMonthlyScore", module_idParameter, audit_type_idParameter);
        }
    
        public virtual ObjectResult<sp_getdropdowndetail_Result> sp_getdropdowndetail(Nullable<int> audit_id)
        {
            var audit_idParameter = audit_id.HasValue ?
                new ObjectParameter("audit_id", audit_id) :
                new ObjectParameter("audit_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getdropdowndetail_Result>("sp_getdropdowndetail", audit_idParameter);
        }
    
        public virtual ObjectResult<sp_getDashboardGraph_Result> sp_getDashboardGraph(Nullable<int> module_id)
        {
            var module_idParameter = module_id.HasValue ?
                new ObjectParameter("module_id", module_id) :
                new ObjectParameter("module_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getDashboardGraph_Result>("sp_getDashboardGraph", module_idParameter);
        }
    
        public virtual ObjectResult<sp_getPendingAudits_Result> sp_getPendingAudits(Nullable<int> user_id, Nullable<int> module_id)
        {
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(int));
    
            var module_idParameter = module_id.HasValue ?
                new ObjectParameter("Module_id", module_id) :
                new ObjectParameter("Module_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getPendingAudits_Result>("sp_getPendingAudits", user_idParameter, module_idParameter);
        }
    
        public virtual ObjectResult<sp_getAuditReport_Result> sp_getAuditReport(Nullable<int> module_id, Nullable<int> user_id)
        {
            var module_idParameter = module_id.HasValue ?
                new ObjectParameter("module_id", module_id) :
                new ObjectParameter("module_id", typeof(int));
    
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getAuditReport_Result>("sp_getAuditReport", module_idParameter, user_idParameter);
        }
    
        public virtual ObjectResult<sp_getCAPAReport_Result> sp_getCAPAReport(Nullable<int> module_id, Nullable<int> audittype_id, Nullable<int> user_id)
        {
            var module_idParameter = module_id.HasValue ?
                new ObjectParameter("module_id", module_id) :
                new ObjectParameter("module_id", typeof(int));
    
            var audittype_idParameter = audittype_id.HasValue ?
                new ObjectParameter("audittype_id", audittype_id) :
                new ObjectParameter("audittype_id", typeof(int));
    
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getCAPAReport_Result>("sp_getCAPAReport", module_idParameter, audittype_idParameter, user_idParameter);
        }
    
        public virtual int sp_saveConfirmAudit(Nullable<int> audit_id, string confirm, Nullable<int> confirm_by, ObjectParameter err_code, ObjectParameter err_msg)
        {
            var audit_idParameter = audit_id.HasValue ?
                new ObjectParameter("audit_id", audit_id) :
                new ObjectParameter("audit_id", typeof(int));
    
            var confirmParameter = confirm != null ?
                new ObjectParameter("confirm", confirm) :
                new ObjectParameter("confirm", typeof(string));
    
            var confirm_byParameter = confirm_by.HasValue ?
                new ObjectParameter("confirm_by", confirm_by) :
                new ObjectParameter("confirm_by", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_saveConfirmAudit", audit_idParameter, confirmParameter, confirm_byParameter, err_code, err_msg);
        }
    
        public virtual ObjectResult<sp_getRoleDetails_Result> sp_getRoleDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getRoleDetails_Result>("sp_getRoleDetails");
        }
    
        public virtual ObjectResult<sp_GetPlanConsolidated_Result> sp_GetPlanConsolidated(Nullable<int> p_location_id, Nullable<int> p_module_id)
        {
            var p_location_idParameter = p_location_id.HasValue ?
                new ObjectParameter("p_location_id", p_location_id) :
                new ObjectParameter("p_location_id", typeof(int));
    
            var p_module_idParameter = p_module_id.HasValue ?
                new ObjectParameter("p_module_id", p_module_id) :
                new ObjectParameter("p_module_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetPlanConsolidated_Result>("sp_GetPlanConsolidated", p_location_idParameter, p_module_idParameter);
        }
    
        public virtual ObjectResult<sp_getConsolidatedAuditStatus_Result> sp_getConsolidatedAuditStatus(Nullable<int> location_id, Nullable<int> module_id, Nullable<int> user_id)
        {
            var location_idParameter = location_id.HasValue ?
                new ObjectParameter("location_id", location_id) :
                new ObjectParameter("location_id", typeof(int));
    
            var module_idParameter = module_id.HasValue ?
                new ObjectParameter("module_id", module_id) :
                new ObjectParameter("module_id", typeof(int));
    
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getConsolidatedAuditStatus_Result>("sp_getConsolidatedAuditStatus", location_idParameter, module_idParameter, user_idParameter);
        }
    }
}
