//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Audire_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_distribution_list
    {
        public int dist_list_id { get; set; }
        public Nullable<int> location_id { get; set; }
        public string list_type { get; set; }
        public string email_list { get; set; }
        public string send_notification_to_owner { get; set; }
    }
}
