//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Audire_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_location_master
    {
        public int location_id { get; set; }
        public Nullable<int> country_id { get; set; }
        public Nullable<int> region_id { get; set; }
        public string location_code { get; set; }
        public string location_name { get; set; }
        public Nullable<System.TimeSpan> shift1_start_time { get; set; }
        public Nullable<System.TimeSpan> shift1_end_time { get; set; }
        public Nullable<System.TimeSpan> shift2_start_time { get; set; }
        public Nullable<System.TimeSpan> shift2_end_time { get; set; }
        public Nullable<System.TimeSpan> shift3_start_time { get; set; }
        public Nullable<System.TimeSpan> shift3_end_time { get; set; }
        public Nullable<int> no_of_shifts { get; set; }
        public string timezone_code { get; set; }
        public string timezone_desc { get; set; }
        public string default_language { get; set; }
    }
}
