//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Audire_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AuditResult
    {
        public int id { get; set; }
        public int audit_id { get; set; }
        public Nullable<int> question_id { get; set; }
        public string answer { get; set; }
        public string audit_comment { get; set; }
        public string assigned_To { get; set; }
        public string audit_images { get; set; }
        public Nullable<int> module_id { get; set; }
        public Nullable<int> region_id { get; set; }
        public Nullable<int> country_id { get; set; }
        public Nullable<int> location_id { get; set; }
        public Nullable<int> line_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> shift_no { get; set; }
        public Nullable<int> audit_performed_by { get; set; }
        public string audit_performed_on { get; set; }
        public Nullable<System.DateTime> audit_performed_date { get; set; }
        public string review_status { get; set; }
        public string review_comment { get; set; }
        public string review_images { get; set; }
        public Nullable<int> reviewed_by { get; set; }
        public string reviewed_on { get; set; }
        public Nullable<System.DateTime> reviewed_date { get; set; }
        public Nullable<int> AuditType_id { get; set; }
        public string Part_name { get; set; }
        public string Auditor_Comment { get; set; }
        public string Audit_number { get; set; }
        public string root_cause { get; set; }
        public string Corrective_Action { get; set; }
        public string Preventive_Action { get; set; }
        public string confirm_comment { get; set; }
        public Nullable<int> confirmed_by { get; set; }
        public Nullable<System.DateTime> confirmed_date { get; set; }
        public string IsCompleted { get; set; }
    }
}
