//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Audire_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_local_answers
    {
        public int loc_answer_id { get; set; }
        public Nullable<int> audit_id { get; set; }
        public Nullable<int> audit_plan_id { get; set; }
        public Nullable<int> audited_by_user_id { get; set; }
        public int line_product_rel_id { get; set; }
        public Nullable<System.DateTime> audit_date { get; set; }
        public Nullable<int> Shift_No { get; set; }
        public Nullable<int> question_id { get; set; }
        public Nullable<int> answer { get; set; }
        public string remarks { get; set; }
        public string image_file_name { get; set; }
        public Nullable<int> review_user_id { get; set; }
        public Nullable<System.DateTime> review_closed_on { get; set; }
        public Nullable<int> review_closed_status { get; set; }
        public string review_comments { get; set; }
        public string review_image_file_name { get; set; }
        public string notification_sent_flag { get; set; }
        public Nullable<int> region_id { get; set; }
        public Nullable<int> country_id { get; set; }
        public Nullable<int> location_id { get; set; }
        public Nullable<int> section_id { get; set; }
        public Nullable<int> line_id { get; set; }
    }
}
