//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Audire_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_audit_type
    {
        public int ID { get; set; }
        public string Audit_Type { get; set; }
        public Nullable<int> module_id { get; set; }
        public Nullable<int> Status { get; set; }
        public string Color_code { get; set; }
        public string Parts { get; set; }
        public Nullable<int> display_seq { get; set; }
    }
}
