//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Audire_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_group_members
    {
        public int group_member_id { get; set; }
        public Nullable<int> location_id { get; set; }
        public Nullable<int> group_id { get; set; }
        public Nullable<int> user_id { get; set; }
    }
}
