//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Audire_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_audit_plan
    {
        public int audit_plan_id { get; set; }
        public Nullable<int> to_be_audited_by_user_id { get; set; }
        public Nullable<System.DateTime> planned_date { get; set; }
        public Nullable<int> shift_no { get; set; }
        public Nullable<int> line_product_rel_id { get; set; }
        public string notification_sent_flag { get; set; }
        public Nullable<int> to_be_audited_by_group_id { get; set; }
        public Nullable<System.DateTime> planned_date_end { get; set; }
        public Nullable<int> line_id { get; set; }
        public Nullable<int> location_id { get; set; }
        public Nullable<int> module_id { get; set; }
        public Nullable<int> Audit_type_id { get; set; }
        public string audit_note { get; set; }
    }
}
